name: Run gitian-builder

on:
  push:
    branches:
      - develop  # Change this to your main branch

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: dsw

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8  

      - name: Prepare env
        run: |
          ls
          cp dsw/contrib/gitian-build.py .
          
      - name: Setup gitian-build
        run: |
          chmod +x gitian-build.py
          ./gitian-build.py --docker --setup

      - name: Run gitian-build
        run: |
          export NAME=$GITHUB_ACTOR
          export BRANCH=develop
          ./gitian-build.py --docker -b -c -o l --detach-sign $NAME $BRANCH -j 12 -m 24000

      - name: Commit and push
        run: |
          mkdir -p dsw/$GITHUB_ACTOR/gitian.sigs
          cp -r dsw-binaries dsw/$GITHUB_ACTOR/
          cp -r gitian.sigs/develop* dsw/$GITHUB_ACTOR/gitian.sigs
          cd dsw
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $GITHUB_ACTOR/dsw-binaries $GITHUB_ACTOR/gitian.sigs
          git commit -m "Commit changes in dsw-binaries and gitian.sigs"
          git push
