name: Run gitian-builder

on:
  #push:
  #  branches:
  #    - develop  # Change this to your main branch
  release:
    types:
      - created  # Trigger the workflow when a new release is created
      
jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: dsw
          
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: zimbora/gitian.sigs
          ref: main  # Adjust to the branch or tag you want to check out
          token: ${{ secrets.PAT_TOKEN }}
          path: gitian.sigs

      - name: Create and Checkout New Branch
        run: |
          BRANCH_NAME="sigs-${GITHUB_ACTOR}"
          git config --global user.email "lucas.ua.eet@gmail.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git checkout -b $BRANCH_NAME
        continue-on-error: true  # This is set to continue if the branch already exists

      - name: Add Files to the Branch
        run: |
          mkdir -p develop-linux/${GITHUB_ACTOR}
          touch develop-linux/${GITHUB_ACTOR}/dsw-linux-6.0-build.assert
          git add .
          git commit -m "Adds sigs"
        continue-on-error: true

      - name: Push Changes to Repository
        run: |
          BRANCH_NAME="sigs-${GITHUB_ACTOR}"
          git push origin $BRANCH_NAME

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8  

      - name: Prepare env
        run: |
          ls
          cp dsw/contrib/gitian-build.py .
          
      - name: Setup gitian-build
        run: |
          chmod +x gitian-build.py
          ./gitian-build.py --docker --setup

      - name: Run gitian-build
        run: |
          export NAME=$GITHUB_ACTOR
          export BRANCH=develop
          ./gitian-build.py --docker -b -c -o l --detach-sign $NAME $BRANCH -j 12 -m 24000

      - name: Commit and push
        run: |
          ls
          mkdir -p dsw/$GITHUB_ACTOR/gitian.sigs
          cp -r dsw-binaries dsw/$GITHUB_ACTOR/
          cp -r gitian.sigs/develop* dsw/gitian.sigs
          cd dsw
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $GITHUB_ACTOR/dsw-binaries $GITHUB_ACTOR/gitian.sigs
*/
